### ISSUE TITLE
0.1.0 release TODOs

### ISSUE THREAD

**Issue by pleerock** [typeorm/typeorm#486]
## Tasks
- [x] implement database specific types for each database
- [x] implement "uuid"|"sequence" generated column on all platforms
- [x] make sure `default: null` is working like `nullable: true`
- [ ] fix closure entity issues and implement closure entity with multiple primary keys
- [ ] implement move/remove methods of the closure entity
- [ ] fix all inheritance-patterns issues
- [ ] entity metadata validator should be finished
- [ ] finish entity schemas, add support for js, xml and yml configurations
- [ ] refactor subject operation builder, persistence and cascades...
- [ ] add relation on update?
- [ ] finish naming strategy, provide naming strategy for old version
- [x] migrations generator
- [x] make ColumnOptions dynamic depend on provided data type
- [x] implement eager relations
- [x] finish logger
- [ ] add logs everywhere (probably need first determine places where logs should be placed)
- [x] create different connection options interfaces depend on driver "type"
- [x] add all possible options from drivers
- [x] add options for connection pooling
- [ ] figure out something with sqlite connections
- [x] figure out strategy for migrations and schema sync
- [x] add cli command to show sql to be executed
- [ ] figure out how to test cli commands and test them
- [x] finish data store in entity manager
- [ ] think if we can implement multiple entities mapped to a single property relation type (`@ManyToMany([Symptom, Disease, Syndrome]) complications: Concept[]`)
- [x] provide api to perform bulk inserts more efficiently 
- [ ] create backup command for cli
- [ ] add ability to create one-to-many relations without inverse side
- [ ] make `query` method non-driver specific
- [x] investigate multiple database queries issue
- [ ] make sure create date / update date are working properly with mongo
- [ ]  implement true relations and joins in mongo
- [x]  reorganize docs to cover both relational and mongo databases
- [ ]  try to add more document storage databases
- [ ]  make sure lazy loading is working with mongo once mongo relations are setup
- [ ]  make sure create date / update date are working properly with mongo
- [x]  investigate multiple database queries issue
- [ ] add persistment options? (like UPDATE_COLUMNS|UPDATE_RELATIONS)?
- [ ] tree repository should be able to work with adjacency list, self referenced relations with tree decorators used
- [ ] fix naming strategy issues, use naming strategy everywhere possible
- [x] pessimistic / optimistic locking?
- [ ] functionality for versioning and revisions?
- [ ] functionality for soft deletion?
- [ ] support nestedset and materialized path
- [x] throw exceptions in persist if entity was updated with a new version/updated date
- [x] add result caching capabilities to query builder
- [ ] internationalization features (for example @internationalization() name can create fields for languages set in the configuration (lets say name_tj, name_ru, name_en, name_es) and during selection only fields of the current internationalization will be selected and mapped to their original name (e.g. name_en mapped to name)
- [ ] add @where and @select decorators
- [ ] implement extend of the entity schemas
- [x] caching strategies
- [x] multiple auto generation strategies?
- [ ] what about in memory strategy and unit of work?
- [ ] fix issue with onDelete is not updated on each run (only initialized on first create)
- [x] logging, allow to provide a custom logger
- [ ] send entity changeset in update event
- [ ] better validation, exceptions everywhere!

## Test Coverage

- [ ] check all data types (persistence and hydration to work correctly)
- [ ] check if not supported column type exception raises
- [ ] check custom column name is working fine
- [ ] check if length can be both string and number
- [ ] check generated to work with both uuid and sequence on all platforms
- [ ] check if generated not supported on platform arise 
- [ ] make sure `default: null` is acceptable and works predicable
- [ ] make sure `default: () => "POW()"` syntax works
- [ ] make sure unique, primary, nullable, default, comment, precision, scale, timezone, fixedLength works on platforms correctly 
- [ ] test CreatedDate / UpdatedDate / Version
- [ ] tests for custom repositories 
- [ ] tests for connection, connection manager, test each connection option available 
- [ ] make sure entity inheritance works correctly and columns are overridden properly if needed
- [ ] completely test-coverage closure entity and its tree repository
- [ ] test entity engine, skip schema sync and order by defined by decorator
- [ ] complete test coverage for entity schemas
- [ ] more tests for lazy relations
- [ ] test naming strategies
- [ ] test entity manager methods
- [ ] test transaction

## Documentation
- [x] provide complete 0.1.0 vs 0.0.x changelog
- [x] tell about lazy relations, eager relations and normal relations - explain differences
- [x] tell about both data mapper and active record patterns support
- [x] tell about composite primary keys support
- [x] tell more about embeds and embeds inside embeds, tell about relations support in embeds
- [x] tell for users who want to create many-to-many with custom columns that they should create entities instead of many-to-many
- [x] better description about indices and unique indices
- [x] tell about join relations that point multiple columns
- [x] tell about many-to-many that can point to multiple columns from both sides
- [x] tell about custom many-to-many table name, custom join column name
- [x] tell how both relation and its join column(s) can be created
- [x] tell about multiple types of generated columns
- [x] tell how make column primary/nullable/with default/default as function, use custom column name, use column length and fixed length, make column unique, add comment, precision and scale.
- [x] tell about embedded prefix
- [x] tell more about transactions, entity manager in transactions and transactional decorator
- [ ] add vanilla javascript documentation
- [ ] add docs about relation id and relation count
- [x] add better docs about query builder and all its new features
- [x] add patterns and best practices section
- [x] add example how to use it with express
- [ ] explain created date / updated date / version columns in details
- [ ] tell about mongodb support
- [ ] tell more about listeners and subscribers
- [ ] tell about naming strategy, tell about container integration
- [ ] tell about custom entity repositories
- [ ] tell about custom logger integration 
- [ ] explain how typeorm connection work, difference with real database connection and connection pooling, when to setup connection
- [ ] explain that there is no need to store typeorm connections, they are all stored in connection manager already and can be easily obtained
- [ ] more about cli commands
- [ ] explain all repository and entity manager methods in details
- [ ] tell about new find options syntax
- [ ] added docs about multiple supported ormconfig types (xml, yml, json, js, env)

This list is not finished yet, will add more items later. Feel free to contribute on any of them, the most important that can help me and at the same time easy for newcomer contributors is test-coverage.

**Comment by 19majkel94** [comment]
I would like to see this list as tasks for projects:
https://github.com/typeorm/typeorm/projects

We could split the tasks to the columns and assign people to each task, track changes, discussion, etc. :wink:

**Comment by pleerock** [comment]
Project setup and each issue setup require lot of efforts. So at the moment (having fact how many people will help me...) its not effective to use it. If someone want to help me, post message here or create a separate issue (or straightly PR) with description and point it in this issue

**Comment by 19majkel94** [comment]
Right, every contributor can create new issue for the choosen task, references this issue and here we can track them on the list by referencing their ids. PR might takie some time and a few contributors might work on the same thing, e.g. you and the new contributor 😉 

What about separate packages for mysql, mongo, etc.? It will be done later after we `implement database specific types for each database`, etc.?

**Comment by pleerock** [comment]
> PR might takie some time so there's a risk that two contributors might work on the same thing at the same time

be more realistic , for such scenario to exist there should be hundred of active contributors 😉. So this wont happen.

> What about separate packages for mysql, mongo, etc.

I don't think this will happen in next and future releases. Too much complex work and brings too much more overhead and maintenance costs. Maybe someday in the future.

**Comment by 19majkel94** [comment]
> Too much complex work and brings too much more overhead and maintenance costs. 
I don't think so, it's like switching from JS to Typescript -  "maintenance costs" and "more overhead" of typing types, interfaces, etc.  

Without this it will be hard to `make ColumnOptions dynamic depend on provided data type` for `implement database specific types for each database`. I mean that using types not supported for mysql and other decorator options. And we don't have to refactor all codebase at once 😉

**Comment by NoNameProvided** [comment]
> having fact how many people will help me...

I would like to be + 1, but nowadays I have so less free time (even the env reader module is not implemented since weeks, shame on me) but as soon as I have some free time, happy to contribute here and with routing-controllers as well.

**Comment by MrGekko** [comment]
I have noticed there is a 0.1.0-alpha2 in https://github.com/typeorm/typeorm/pull/337. Is there a specific branch the 0.1.0 is going to be worked at?

**Comment by pleerock** [comment]
right now work is in progress on #337 Probably better to do things on this branch

**Comment by oriolgual** [comment]
Is the `@where` decorator something to specify the conditions to load a relation? If so it would be great. I just started using TypeORM, but if you point me to what I should look at I could try to send a PR for it.

**Comment by felipesabino** [comment]
Is there plan for an intermediate release? There are so many cool features already on the alpha version that I wonder if all these feature TODOs are actually needed for the `0.1.0` release.

The things I am most concerned about right now are the issues fixed at `0.1.0 alpha`/`master`/`latest` with no plans to be fixed on current stable (for example #536) and the lack of a deadline/estimate for a final release.

I have been using TypeORM in production it's been several months and knowing that the master releases are _unstable_ and also not knowing what is the difference between the dozens of alpha releases current on npm (currently on `33`), makes it hard to justify the cost of going through the pain of all the breaking changes introduced in the _latest_ version on a stable product.

Also, the recent move to stagnate the stable version for several months (`0.0.11` was released more than 4 months ago) is really frustrating in a contribution point of view, as there is no light in the dark about when all these commits/PR will ever be released. 

The codebase is not that small and I agree that splitting drivers in different libs would make it much easier for contributors, but how long will it take? Can't we do this incrementally? May be after a stable release do each driver at a time?

The same goer for other item on this list, are they really a *must* have or just just nice to have? For example, _ [ ] add @where and @select decorators_ i a feature I would love to use, specially when dealing with soft delete and related entities, but should we stop all other goodies that are ready to be shipped in order to develop this? Is this more important *now* than having a good documentation on what is already developed?

After using this lib for a little while I became more familiar with the codebase on a point that I could start contributing, but unfortunately I must confess that it became more feasible to just workaround some issues in my projects using the stable version of TypeORM than to go through the trouble of sending a PR. Especially, of course, because most of the problems were already solved.

TypeORM is such an awesome and useful piece of software that it frustrates not being able or, actually, not knowing how to help move it forward in the way it could. So I also ask, what can contributors do to at this point help and get more frequent releases back on track faster?

**Comment by pleerock** [comment]
> and knowing that the master releases are unstable

I don't think they should be called "unstable". Latest master versions (alpha) are much more stable then 0.0.11 because of how many fixes were made already. Unfortunately there are some functionality broken (really really complex part of orm) but they are so hardly to fix that Im thinking to postpone them to 0.2.0 version. People asked several times what version to use and answer is always same - use 0.1.0.alpha.

> not knowing what is the difference between the dozens of alpha releases

I document the most important change in changelog in order as they appear

> The codebase is not that small and I agree that splitting drivers in different libs would make it much easier for contributors, but how long will it take? Can't we do this incrementally? May be after a stable release do each driver at a time?

latest decision was to cancel this splitting at all. And I don't plan to do it this and maybe even next year.

> I became more familiar with the codebase on a point that I could start contributing

start. Use master for both your development and contribution.

> There are so many cool features already on the alpha version that I wonder if all these feature TODOs are actually needed for the 0.1.0 release.

No, they all won't be released in 0.1.0. Most of what I wanted to be released in 0.1.0 is already done, there are some features left to implement. I expect 0.1.0 release probably in september-october.

**Comment by felipesabino** [comment]
> Use master for both your development and contribution.

Would you recommend using master releases (`aka 0.1.0-alphaX`) for production? 

> I don't think they should be called "unstable".
> use 0.1.0.alpha.

So could we release it as is, follow semver from now on for future increments/features/fixes and then have a detailed changelog for each minor version? 

There is no way today to know what is different from `0.1.0-alpha32` and `0.1.0-alpha33`, for example and if anyone were to use it on production, I suspect they need to be comfortable knowing exactly what changed from version X to Y and how that affects their system. Now semver is completetly ignored for `-alpha` versions, so there is no guarantee that upgrading from `-alpha32` to `-alpha32` due to an minor fix won't break the API compatibility. that said, there is no way to be comfortable on having just `0.1.0-apha`


> Most of what I wanted to be released in 0.1.0 is already done, there are some features left to implement. I expect 0.1.0 release probably in september-october.

Awesome, that's great news! Can you share which ones they are or just point us to the right direction so that we can help prioritize and help achieving it earlier?

**Comment by pleerock** [comment]
> Would you recommend using master releases (aka 0.1.0-alphaX) for production?

I do use it.

> So could we release it as is, follow semver from now on for future increments/features/fixes and then have a detailed changelog for each minor version?

I understand your point about 0.1.0-alpha32 and 0.1.0-alpha33 missing changelog. I understand this can be unpleasant. But "detailed changelog" takes time. I would like to skip as much as possible extra efforts and work until all planned features arent released and framework isnt completely ready. So for now I provide as much changelog as I think needed. And yeah its not detailed at some points. I'll be glad if someone wants to take this bureaucracy on his own.

>  Can you share which ones they are or just point us to the right direction so that we can help prioritize and help achieving it earlier?

Tasks which left for final 0.1.0 are mostly about persistment and cascades - there are quite big issues there and only I can fix them (due to complexity and orm deep knowledge requirements). It may take me few month to fix them I guess. I don't think anyone can help me

But I'll be glad if anyone can help me with any other tasks typeorm has. If you are really interested and ready for concrete implementation I'll mark some issues needs to be done by community (which do not require deep orm knowledge I mean)

**Comment by pleerock** [comment]
I'll close it since 0.1.0 is released. All left tasks are moved into roadmap, you can find in on the site.
